name: CI/CD Pipeline for WordPress on EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker pull wordpress:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run basic test
      run: |
        echo "Running basic test..."
        docker pull wordpress:latest
        docker run --rm wordpress:latest --version

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name cluster-toolzz --region us-east-1

    - name: Deploy WordPress to EKS
      run: |
        kubectl apply -f eks/deployment.yaml
        kubectl apply -f eks/service.yaml